import { UserProfile, JobOpportunity, MockTest, DailyTask, LeaveRequest, AIAgentStatus } from '../types';
import { getCompanyPortalDeepLink } from '../utils/jobLinks';

// Clean initial student profile awaiting resume upload & parsing
export const unparsedStudentProfile: UserProfile = {
  name: 'Student Candidate',
  email: 'student@college.edu',
  phone: '+91 98765 00000',
  college: 'Engineering University',
  department: '',
  graduationYear: 2026,
  cgpa: 0,
  backlogs: 0,
  codingLevel: 'Beginner',
  communicationScore: 0,
  preferredCompanies: [],
  preferredRoles: [],
  preferredCities: [],
  technicalSkills: [],
  softSkills: [],
  languages: ['English'],
  certifications: [],
  projects: [],
  github: '',
  linkedin: '',
  portfolio: '',
  placementReadinessScore: 0,
  employabilityScore: 0,
  atsScore: 0,
  dailyStreak: 0,
  isOnboarded: false,
  resumeFileName: '',
  resumeUploadedAt: ''
};

export const initialStudentProfile = unparsedStudentProfile;

export const sampleAIAgentStatus: AIAgentStatus = {
  agentName: 'PlacementOS AI Assistant v4.2',
  status: 'Active Monitoring',
  lastScanTime: 'Today at 06:00 AM',
  todayMatchingJobsCount: 15,
  todayInternshipsCount: 4,
  todayMockTestsCount: 1,
  todayInterviewsCount: 1,
  monitoredCompanies: ['Google', 'Zoho', 'Microsoft', 'TCS', 'Amazon', 'Texas Instruments', 'Schneider Electric', 'Ubisoft', 'EA Games', 'Rockstar Games', 'Tata Motors', 'LinkedIn Feed', 'Naukri Feed'],
  monitoredCities: ['Bengaluru', 'Chennai', 'Hyderabad', 'Pune']
};

export const sampleLeaveRequests: LeaveRequest[] = [
  {
    id: 'leave-1',
    studentId: 'stud-101',
    studentName: 'Candidate Student',
    department: 'Computer Science & Engineering',
    companyName: 'Zoho Corporation',
    interviewRole: 'Software Developer (Final Round)',
    leaveDate: '2026-08-02',
    reason: 'Attending on-site physical technical interview at Zoho Campus, Chennai.',
    status: 'Pending',
    appliedDate: '2026-07-27'
  }
];

export const sampleRecruiterCandidates = [
  {
    id: 'cand-101',
    name: 'Arun Kumar',
    department: 'Computer Science & Engineering',
    cgpa: 8.85,
    backlogs: 0,
    skills: ['React', 'TypeScript', 'Node.js', 'Python', 'SQL', 'MongoDB'],
    readinessScore: 88,
    atsScore: 84,
    codingLevel: 'Advanced',
    email: 'arun.k@college.edu',
    phone: '+91 98765 43210',
    resumeUrl: '#',
    location: 'Bengaluru / Chennai'
  },
  {
    id: 'cand-102',
    name: 'Karthik Raja',
    department: 'Electrical & Electronics Engineering',
    cgpa: 8.45,
    backlogs: 0,
    skills: ['C', 'C++', 'Microcontrollers', 'Python', 'Embedded Systems', 'RTOS'],
    readinessScore: 82,
    atsScore: 78,
    codingLevel: 'Intermediate',
    email: 'karthik.r@college.edu',
    phone: '+91 98765 44332',
    resumeUrl: '#',
    location: 'Bengaluru'
  }
];

export const sampleJobs: JobOpportunity[] = [
  // --- GAME DEV & 3D ARTIST (UNITY, BLENDER, 3D ARTIST) ---
  {
    id: 'job-ubisoft-1',
    company: 'Ubisoft Entertainment',
    role: 'Unity 3D Developer & Game Graphics Engineer',
    officialSiteRoleName: 'Ubisoft Careers: Unity 3D & Graphics Software Engineer',
    linkedInRoleName: 'LinkedIn: Unity 3D Developer (Pune Studios)',
    naukriRoleName: 'Naukri: Game Programmer - Unity 3D / C#',
    indeedRoleName: 'Indeed: Associate Unity 3D Game Engineer',
    socialMediaRoleName: 'Twitter/X: Ubisoft India Unity 3D Hiring Drive',
    description: 'Design and optimize 3D gameplay systems, custom shaders, and real-time graphics rendering engines for AAA game titles using Unity and C#.',
    department: 'Electrical & Electronics Engineering',
    skillsRequired: ['UNITY', 'BLENDER', 'GAME DEVELOPMENT', '3D ARTIST', 'C#', 'C++'],
    salary: '₹14,50,000 / yr',
    location: 'Pune / Mumbai (Hybrid)',
    experience: 'Fresher (2026 Batch)',
    education: 'B.E / B.Tech / Any Graduate',
    minCgpa: 6.5,
    maxBacklogs: 0,
    openDate: '2026-07-20',
    closeDate: '2026-09-25',
    lastDate: '2026-09-25',
    vacancies: '15 Openings',
    applyLink: 'https://www.ubisoft.com/en-us/company/careers',
    source: 'LinkedIn Verified Jobs',
    isInternship: false,
    postedDate: 'Posted 1h ago via LinkedIn',
    verifiedDate: 'Verified Live Feed',
    status: 'Verified',
    matchPercentage: 100,
    missingSkills: [],
    eligible: true,
    estimatedInterviewProbability: 96
  },
  {
    id: 'job-ea-1',
    company: 'EA Games (Electronic Arts)',
    role: 'Associate 3D Modeler & Unity Interactive Developer',
    officialSiteRoleName: 'EA Careers: Associate 3D Artist & Interactive Developer',
    linkedInRoleName: 'LinkedIn: 3D Modeler & Unity Developer - EA India',
    naukriRoleName: 'Naukri: 3D Artist & Game Engine Developer (EA)',
    indeedRoleName: 'Indeed: Associate 3D Modeler - Electronic Arts',
    socialMediaRoleName: 'Glassdoor: EA Games 3D Artist Opening 2026',
    description: 'Model high-fidelity 3D game assets in Blender/Maya and integrate them into Unity interactive game environments with custom texture mapping.',
    department: 'Electrical & Electronics Engineering',
    skillsRequired: ['UNITY', 'BLENDER', '3D ARTIST', 'GAME DEVELOPMENT', 'Maya', 'Shader Programming'],
    salary: '₹16,50,000 / yr',
    location: 'Hyderabad (EA India)',
    experience: 'Fresher (0-1 yr)',
    education: 'B.Tech / B.E / B.Sc',
    minCgpa: 7.0,
    maxBacklogs: 0,
    openDate: '2026-07-22',
    closeDate: '2026-09-22',
    lastDate: '2026-09-22',
    vacancies: '10 Openings',
    applyLink: 'https://www.ea.com/careers/careers-overview#search=3D%20Modeler',
    source: 'Naukri Verified Jobs',
    isInternship: false,
    postedDate: 'Posted 3h ago via Naukri',
    verifiedDate: 'Verified Naukri Feed',
    status: 'Verified',
    matchPercentage: 98,
    missingSkills: ['Maya'],
    eligible: true,
    estimatedInterviewProbability: 94
  },
  {
    id: 'job-rockstar-1',
    company: 'Rockstar Games India',
    role: 'Game Physics & Shader Renderer Developer',
    officialSiteRoleName: 'Rockstar Careers: Physics & Graphics Programmer',
    linkedInRoleName: 'LinkedIn: Game Physics Programmer (Rockstar Bengaluru)',
    naukriRoleName: 'Naukri: Game Shader & Physics Engineer',
    indeedRoleName: 'Indeed: C++ Game Physics Developer - Rockstar',
    socialMediaRoleName: 'Twitter/X: Rockstar Games India Graphics Tech Hiring',
    description: 'Implement complex rigid-body physics simulation algorithms, particle effects, and HLSL/GLSL shader pipelines for next-gen open world engines.',
    department: 'Electrical & Electronics Engineering',
    skillsRequired: ['UNITY', 'BLENDER', '3D ARTIST', 'GAME DEVELOPMENT', 'C++'],
    salary: '₹18,00,000 / yr',
    location: 'Bengaluru (Rockstar India)',
    experience: 'Fresher (0-2 yrs)',
    education: 'B.E / B.Tech / MCA',
    minCgpa: 7.0,
    maxBacklogs: 0,
    openDate: '2026-07-25',
    closeDate: '2026-09-30',
    lastDate: '2026-09-30',
    vacancies: '8 Openings',
    applyLink: 'https://www.rockstargames.com/careers/openings?q=Game%20Physics',
    source: 'Official Company Careers',
    isInternship: false,
    postedDate: 'Posted 4h ago',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 95,
    missingSkills: [],
    eligible: true,
    estimatedInterviewProbability: 92
  },

  // --- ELECTRICAL & ELECTRONICS (EEE / ECE) ---
  {
    id: 'job-schneider-1',
    company: 'Schneider Electric',
    role: 'Electrical & Power Automation Engineer GET',
    officialSiteRoleName: 'Schneider Careers: Graduate Engineer Trainee - Power Automation',
    linkedInRoleName: 'LinkedIn: Electrical Automation GET (Bengaluru/Chennai)',
    naukriRoleName: 'Naukri: Schneider Electrical Automation Engineer',
    indeedRoleName: 'Indeed: GET Electrical & Power Systems',
    socialMediaRoleName: 'Twitter/X: Schneider Electric GET Campus Drive 2026',
    description: 'Engineer sub-station power control logic, configure industrial PLCs, and test smart grid automation hardware using MATLAB and C++.',
    department: 'Electrical & Electronics Engineering',
    skillsRequired: ['Electrical Power Systems', 'PLC Programming', 'MATLAB', 'C++', 'Embedded Systems', 'Circuit Design'],
    salary: '₹12,50,000 / yr',
    location: 'Bengaluru / Chennai',
    experience: 'Fresher (GET 2026)',
    education: 'B.E / B.Tech EEE, ECE',
    minCgpa: 7.0,
    maxBacklogs: 0,
    openDate: '2026-07-26',
    closeDate: '2026-09-20',
    lastDate: '2026-09-20',
    vacancies: '25 Openings',
    applyLink: 'https://www.se.com/ww/en/about-us/careers/',
    source: 'Official Company Careers',
    isInternship: false,
    postedDate: 'Posted 3 days ago',
    verifiedDate: 'Verified Today at 08:30 AM',
    status: 'Verified',
    matchPercentage: 92,
    missingSkills: [],
    eligible: true,
    estimatedInterviewProbability: 92
  },
  {
    id: 'job-ti-1',
    company: 'Texas Instruments',
    role: 'Embedded Systems & Firmware Engineer',
    officialSiteRoleName: 'TI Careers: Systems & Firmware Applications Engineer',
    linkedInRoleName: 'LinkedIn: Embedded Systems Firmware Engineer (Bengaluru)',
    naukriRoleName: 'Naukri: TI Microcontroller & Embedded Firmware Dev',
    indeedRoleName: 'Indeed: Embedded C/C++ Engineer - Texas Instruments',
    socialMediaRoleName: 'Glassdoor: TI Embedded Systems Engineer Hiring',
    description: 'Develop low-level device drivers, ARM Cortex-M micro-controller firmware, and real-time operating system (RTOS) kernels in C/C++.',
    department: 'Electrical & Electronics Engineering',
    skillsRequired: ['C', 'C++', 'Microcontrollers', 'RTOS', 'Embedded Systems', 'ARM Architecture'],
    salary: '₹18,50,000 / yr',
    location: 'Bengaluru',
    experience: 'Fresher / 0-2 yrs',
    education: 'B.E / B.Tech EEE, ECE',
    minCgpa: 7.5,
    maxBacklogs: 0,
    openDate: '2026-07-28',
    closeDate: '2026-09-01',
    lastDate: '2026-09-01',
    vacancies: '30 Openings',
    applyLink: 'https://careers.ti.com/',
    source: 'Official Company Careers',
    isInternship: false,
    postedDate: 'Posted 4 days ago',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 88,
    missingSkills: ['RTOS'],
    eligible: true,
    estimatedInterviewProbability: 85
  },

  // --- CSE / IT DEPT ---
  {
    id: 'job-google-1',
    company: 'Google',
    role: 'Associate Software Engineer - 2026 Batch',
    officialSiteRoleName: 'Google Careers: Software Engineer, University Graduate 2026',
    linkedInRoleName: 'LinkedIn: Associate Software Engineer (Bengaluru/Hyderabad)',
    naukriRoleName: 'Naukri: Google Software Development Engineer 2026',
    indeedRoleName: 'Indeed: Software Engineer University Grad - Google',
    socialMediaRoleName: 'Twitter/X: @GoogleCareers University Grad Hiring 2026',
    description: 'Build robust scalable cloud services, algorithmic data pipelines, and web platforms using C++, Python, and React in an agile team.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['Data Structures', 'Algorithms', 'Python', 'React', 'C++', 'Node.js'],
    salary: '₹28,00,000 / yr',
    location: 'Bengaluru / Hyderabad (Hybrid)',
    experience: 'Fresher (0-1 yr)',
    education: 'B.Tech / B.E. CSE, IT, ECE, EEE',
    minCgpa: 8.0,
    maxBacklogs: 0,
    openDate: '2026-07-28',
    closeDate: '2026-08-30',
    lastDate: '2026-08-30',
    vacancies: '50 Openings',
    applyLink: 'https://careers.google.com/jobs/results/?q=Software%20Engineer',
    source: 'Official Company Careers',
    isInternship: false,
    postedDate: 'Posted 2h ago',
    verifiedDate: 'Verified Today at 08:00 AM',
    status: 'Verified',
    matchPercentage: 94,
    missingSkills: ['C++'],
    eligible: true,
    estimatedInterviewProbability: 88
  },
  {
    id: 'job-zoho-1',
    company: 'Zoho Corporation',
    role: 'Software Developer (Member Technical Staff)',
    officialSiteRoleName: 'Zoho Careers: Member Technical Staff - Software Development',
    linkedInRoleName: 'LinkedIn: Software Developer MTS (Chennai/Tenkasi)',
    naukriRoleName: 'Naukri: Zoho Software Developer Campus Drive',
    indeedRoleName: 'Indeed: Member Technical Staff - Zoho Corp',
    socialMediaRoleName: 'Twitter/X: @Zoho Member Technical Staff Drive',
    description: 'Construct high-throughput web software engines, database backend models in Java, and intuitive interactive UIs in React.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['Java', 'Data Structures', 'C', 'Problem Solving', 'SQL', 'React'],
    salary: '₹8,50,000 / yr',
    location: 'Chennai / Tenkasi / Coimbatore',
    experience: '0 - 2 yrs',
    education: 'BE / B.Tech / MCA / B.Sc',
    minCgpa: 7.0,
    maxBacklogs: 0,
    openDate: '2026-07-27',
    closeDate: '2026-09-15',
    lastDate: '2026-09-15',
    vacancies: '120 Openings',
    applyLink: 'https://www.zoho.com/careers/',
    source: 'Official Company Careers',
    isInternship: false,
    postedDate: 'Posted 4h ago',
    verifiedDate: 'Verified Today at 08:15 AM',
    status: 'Verified',
    matchPercentage: 92,
    missingSkills: ['C'],
    eligible: true,
    estimatedInterviewProbability: 95
  },
  {
    id: 'job-linkedin-msft-1',
    company: 'Microsoft',
    role: 'Full Stack Cloud Developer (Azure)',
    officialSiteRoleName: 'Microsoft Careers: Software Engineer - Cloud & AI',
    linkedInRoleName: 'LinkedIn: Full Stack Cloud Developer (Microsoft Azure)',
    naukriRoleName: 'Naukri: Microsoft Software Engineer - Azure Cloud',
    indeedRoleName: 'Indeed: Full Stack Software Engineer - Microsoft',
    socialMediaRoleName: 'Glassdoor: Microsoft Azure Full Stack Software Engineer',
    description: 'Architect web services and API endpoints on Azure Cloud microservices using TypeScript, Node.js, C#, and React.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['TypeScript', 'React', 'Node.js', 'Azure', 'C#', 'SQL'],
    salary: '₹24,00,000 / yr',
    location: 'Bengaluru / Hyderabad',
    experience: 'Fresher (2026 Batch)',
    education: 'B.Tech / B.E / M.Tech',
    minCgpa: 8.0,
    maxBacklogs: 0,
    openDate: '2026-07-29',
    closeDate: '2026-09-10',
    lastDate: '2026-09-10',
    vacancies: '35 Openings',
    applyLink: 'https://www.linkedin.com/jobs/view/microsoft-software-engineer-2026',
    source: 'LinkedIn Verified Jobs',
    isInternship: false,
    postedDate: 'Posted 1h ago via LinkedIn Jobs Feed',
    verifiedDate: 'Verified Live API',
    status: 'Verified',
    matchPercentage: 96,
    missingSkills: ['Azure'],
    eligible: true,
    estimatedInterviewProbability: 90
  },
  {
    id: 'job-naukri-tcs-1',
    company: 'TCS Digital',
    role: 'Full Stack & AI Engineer (TCS Digital Drive)',
    officialSiteRoleName: 'TCS NextStep: TCS Digital Technical Specialist',
    linkedInRoleName: 'LinkedIn: TCS Digital Full Stack & AI Cadre',
    naukriRoleName: 'Naukri: TCS Digital Cadre Hiring 2026 (7.5 LPA)',
    indeedRoleName: 'Indeed: Full Stack Engineer - TCS Digital',
    socialMediaRoleName: 'Twitter/X: TCS Digital Hiring Drive 2026 Announcement',
    description: 'Develop full stack cloud solutions and AI-driven automation tools using Python, React, Java, and SQL for global enterprise clients.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['Python', 'React', 'Java', 'SQL', 'Git', 'Data Structures'],
    salary: '₹7,50,000 / yr',
    location: 'Chennai / Bengaluru / Pune / Hyderabad',
    experience: 'Fresher (TCS NQT 2026)',
    education: 'B.E / B.Tech / MCA',
    minCgpa: 6.5,
    maxBacklogs: 0,
    openDate: '2026-07-26',
    closeDate: '2026-09-25',
    lastDate: '2026-09-25',
    vacancies: '200 Openings',
    applyLink: 'https://www.naukri.com/tcs-digital-jobs-2026',
    source: 'Naukri Verified Jobs',
    isInternship: false,
    postedDate: 'Posted 5h ago via Naukri.com',
    verifiedDate: 'Verified Naukri Feed',
    status: 'Verified',
    matchPercentage: 95,
    missingSkills: [],
    eligible: true,
    estimatedInterviewProbability: 94
  },
  {
    id: 'job-tata-motors-1',
    company: 'Tata Motors',
    role: 'EV Powertrain & Mechanical Design GET',
    officialSiteRoleName: 'Tata Motors Careers: Graduate Engineer Trainee - EV & Mechanical',
    linkedInRoleName: 'LinkedIn: EV Powertrain Mechanical GET',
    naukriRoleName: 'Naukri: Tata Motors Mechanical Design GET Drive',
    indeedRoleName: 'Indeed: Mechanical Engineering GET - Tata Motors',
    socialMediaRoleName: 'Twitter/X: Tata Motors EV Design Campus Drive',
    description: 'Design electric vehicle battery cooling assemblies, chassis stress simulations, and mechanical CAD models in SolidWorks and CATIA.',
    department: 'Mechanical Engineering',
    skillsRequired: ['AutoCAD', 'SolidWorks', 'CATIA', 'FEA', 'Thermodynamics'],
    salary: '₹9,00,000 / yr',
    location: 'Pune / Chennai',
    experience: 'Fresher (GET 2026)',
    education: 'B.E / B.Tech Mechanical',
    minCgpa: 7.0,
    maxBacklogs: 0,
    openDate: '2026-07-24',
    closeDate: '2026-09-15',
    lastDate: '2026-09-15',
    vacancies: '40 Openings',
    applyLink: 'https://www.tatamotors.com/careers/',
    source: 'Official Company Careers',
    isInternship: false,
    postedDate: 'Posted 1d ago',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 87,
    missingSkills: ['CATIA'],
    eligible: true,
    estimatedInterviewProbability: 90
  },
  {
    id: 'job-indeed-lt-1',
    company: 'L&T Construction',
    role: 'Structural Analysis & BIM Civil GET',
    officialSiteRoleName: 'L&T Careers: Graduate Engineer Trainee - Structural & BIM',
    linkedInRoleName: 'LinkedIn: Civil Structural GET (L&T Construction)',
    naukriRoleName: 'Naukri: L&T Civil Engineering GET Hiring 2026',
    indeedRoleName: 'Indeed: Structural Analysis Civil GET - L&T',
    socialMediaRoleName: 'Glassdoor: L&T Civil Engineering Trainee Opening',
    description: 'Perform structural stress modeling using STAAD Pro, develop 3D Building Information Models (BIM) in REVIT, and manage site concrete specifications.',
    department: 'Civil Engineering',
    skillsRequired: ['AutoCAD', 'STAAD Pro', 'REVIT', 'Structural Analysis', 'Concrete Technology'],
    salary: '₹7,80,000 / yr',
    location: 'Chennai / Mumbai',
    experience: 'Fresher (GET 2026 Batch)',
    education: 'B.E / B.Tech Civil',
    minCgpa: 6.8,
    maxBacklogs: 0,
    openDate: '2026-07-25',
    closeDate: '2026-09-18',
    lastDate: '2026-09-18',
    vacancies: '30 Openings',
    applyLink: 'https://www.larsentoubro.com/corporate/careers/',
    source: 'Indeed Verified Jobs',
    isInternship: false,
    postedDate: 'Posted 4h ago via Indeed',
    verifiedDate: 'Verified Indeed Feed',
    status: 'Verified',
    matchPercentage: 89,
    missingSkills: ['REVIT'],
    eligible: true,
    estimatedInterviewProbability: 91
  },

  // --- WORLDWIDE PAID INTERNSHIPS ---
  {
    id: 'intern-google-1',
    company: 'Google',
    role: 'Software Engineering Summer Intern 2026',
    officialSiteRoleName: 'Google Careers: Software Engineering Intern 2026',
    linkedInRoleName: 'LinkedIn: Software Engineering Intern (Mountain View / Bengaluru)',
    naukriRoleName: 'Naukri: Google SWE Internship Drive 2026',
    indeedRoleName: 'Indeed: Google SWE Intern',
    socialMediaRoleName: 'Twitter/X: Google Students SWE Internship 2026',
    description: 'Work alongside Google engineers building large-scale distributed systems, AI search infrastructure, and cloud APIs. High performance converts to full-time PPO.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['Python', 'Java', 'C++', 'Data Structures', 'Algorithms', 'SQL'],
    salary: '₹1,25,000 / mo (Stipend)',
    location: 'Mountain View, USA / Bengaluru (Hybrid / Remote)',
    experience: 'Internship (2026 Batch)',
    education: 'B.E / B.Tech / M.Tech',
    minCgpa: 7.5,
    maxBacklogs: 0,
    openDate: '2026-07-28',
    closeDate: '2026-10-15',
    lastDate: '2026-10-15',
    vacancies: '60 Openings',
    applyLink: 'https://careers.google.com/jobs/results/?q=Software%20Engineer%20Intern',
    source: 'Official Company Careers',
    isInternship: true,
    postedDate: 'Posted 2h ago via Google Careers',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 96,
    missingSkills: [],
    eligible: true,
    estimatedInterviewProbability: 92
  },
  {
    id: 'intern-microsoft-1',
    company: 'Microsoft',
    role: 'AI Research & SDE Paid Intern',
    officialSiteRoleName: 'Microsoft Careers: Research & Software Engineer Intern',
    linkedInRoleName: 'LinkedIn: Microsoft SDE Intern (Redmond / Hyderabad)',
    naukriRoleName: 'Naukri: Microsoft Research Intern 2026',
    indeedRoleName: 'Indeed: Microsoft SDE Intern',
    socialMediaRoleName: 'Twitter/X: Microsoft Campus Intern Drive 2026',
    description: 'Design generative AI model pipelines and Azure cloud microservices with Microsoft Research teams.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['Python', 'C++', 'PyTorch', 'Data Structures', 'Azure', 'Machine Learning'],
    salary: '₹1,10,000 / mo (Stipend)',
    location: 'Redmond, USA / Hyderabad (Hybrid)',
    experience: 'Internship (2026 / 2027)',
    education: 'B.E / B.Tech / Dual Degree',
    minCgpa: 8.0,
    maxBacklogs: 0,
    openDate: '2026-07-27',
    closeDate: '2026-10-10',
    lastDate: '2026-10-10',
    vacancies: '45 Openings',
    applyLink: 'https://careers.microsoft.com/v2/global/en/search.html?q=Software%20Engineer%20Intern',
    source: 'LinkedIn Verified Jobs',
    isInternship: true,
    postedDate: 'Posted 3h ago',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 94,
    missingSkills: [],
    eligible: true,
    estimatedInterviewProbability: 90
  },
  {
    id: 'intern-zoho-1',
    company: 'Zoho Corporation',
    role: 'Product Development & Full Stack Intern',
    officialSiteRoleName: 'Zoho Careers: Product Developer Intern',
    linkedInRoleName: 'LinkedIn: Zoho Software Developer Intern',
    naukriRoleName: 'Naukri: Zoho Product Developer Internship',
    indeedRoleName: 'Indeed: Zoho Full Stack Intern',
    socialMediaRoleName: 'Twitter/X: Zoho Campus Internship Drive',
    description: 'Develop enterprise SaaS modules, Java backend servlets, and React frontend UI components for Zoho suite apps.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['Java', 'React', 'JavaScript', 'SQL', 'Data Structures'],
    salary: '₹40,000 / mo (Stipend)',
    location: 'Chennai / Tenkasi (India)',
    experience: 'Internship (Pre-Final / Final Year)',
    education: 'B.E / B.Tech / MCA',
    minCgpa: 6.5,
    maxBacklogs: 0,
    openDate: '2026-07-29',
    closeDate: '2026-10-01',
    lastDate: '2026-10-01',
    vacancies: '80 Openings',
    applyLink: 'https://www.zoho.com/careers/',
    source: 'Official Company Careers',
    isInternship: true,
    postedDate: 'Posted 1h ago',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 98,
    missingSkills: [],
    eligible: true,
    estimatedInterviewProbability: 95
  },
  {
    id: 'intern-tesla-1',
    company: 'Tesla Motors',
    role: 'EV Battery & Robotics Software Intern',
    officialSiteRoleName: 'Tesla Careers: EV Battery & Software Engineer Intern',
    linkedInRoleName: 'LinkedIn: Tesla Robotics & EV Intern (Palo Alto)',
    naukriRoleName: 'Naukri: Tesla EV Hardware Intern',
    indeedRoleName: 'Indeed: Tesla Robotics Intern',
    socialMediaRoleName: 'Twitter/X: Tesla Internship Applications Open',
    description: 'Optimize electric powertrain thermal management code and automated robotic arm firmware for Giga-factories.',
    department: 'Electrical & Electronics Engineering',
    skillsRequired: ['C++', 'Python', 'Embedded Systems', 'Microcontrollers', 'Robotics', 'MATLAB'],
    salary: '$5,000 / mo (Stipend)',
    location: 'Palo Alto, USA / Remote Worldwide',
    experience: 'Internship (2026 Batch)',
    education: 'B.E / B.Tech EEE, ECE, Mech',
    minCgpa: 7.5,
    maxBacklogs: 0,
    openDate: '2026-07-26',
    closeDate: '2026-10-20',
    lastDate: '2026-10-20',
    vacancies: '25 Openings',
    applyLink: 'https://www.linkedin.com/jobs/search/?keywords=Tesla%20Intern',
    source: 'LinkedIn Verified Jobs',
    isInternship: true,
    postedDate: 'Posted 5h ago',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 93,
    missingSkills: [],
    eligible: true,
    estimatedInterviewProbability: 88
  },

  // --- WORLDWIDE FULL-TIME ROLES ---
  {
    id: 'job-apple-1',
    company: 'Apple',
    role: 'iOS & Swift Core Systems Engineer',
    officialSiteRoleName: 'Apple Careers: iOS Core OS & Swift Systems Engineer',
    linkedInRoleName: 'LinkedIn: Apple iOS Systems Engineer (Cupertino)',
    naukriRoleName: 'Naukri: Apple Swift Developer',
    indeedRoleName: 'Indeed: Apple iOS Software Engineer',
    socialMediaRoleName: 'Twitter/X: Apple Core OS Engineering Hiring',
    description: 'Engineer low-level iOS kernel extensions, metal graphics rendering frameworks, and Swift high-performance UI libraries.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['Swift', 'C++', 'Objective-C', 'iOS', 'Data Structures', 'Algorithms'],
    salary: '$145,000 / yr',
    location: 'Cupertino, USA / Remote Worldwide',
    experience: 'Fresher / 0-2 yrs',
    education: 'B.E / B.Tech / M.S',
    minCgpa: 7.5,
    maxBacklogs: 0,
    openDate: '2026-07-25',
    closeDate: '2026-10-10',
    lastDate: '2026-10-10',
    vacancies: '20 Openings',
    applyLink: 'https://www.linkedin.com/jobs/search/?keywords=Apple%20Software%20Engineer',
    source: 'Official Company Careers',
    isInternship: false,
    postedDate: 'Posted 6h ago',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 91,
    missingSkills: ['Swift'],
    eligible: true,
    estimatedInterviewProbability: 89
  },
  {
    id: 'job-nvidia-1',
    company: 'NVIDIA',
    role: 'CUDA Graphics & AI Hardware Acceleration Developer',
    officialSiteRoleName: 'NVIDIA Careers: CUDA & System Software Engineer',
    linkedInRoleName: 'LinkedIn: NVIDIA CUDA Developer (Santa Clara / Munich)',
    naukriRoleName: 'Naukri: NVIDIA GPU Compiler & CUDA Engineer',
    indeedRoleName: 'Indeed: NVIDIA Graphics Programmer',
    socialMediaRoleName: 'Twitter/X: NVIDIA AI Architecture Hiring 2026',
    description: 'Optimize parallel computing algorithms on NVIDIA Hopper & Blackwell GPU architectures using C++ and CUDA libraries.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['C++', 'CUDA', 'Python', 'Computer Architecture', 'Parallel Computing', 'GPU'],
    salary: '$160,000 / yr',
    location: 'Santa Clara, USA / Munich, Germany (Hybrid)',
    experience: 'Fresher / 0-2 yrs',
    education: 'B.E / B.Tech / M.Tech',
    minCgpa: 8.0,
    maxBacklogs: 0,
    openDate: '2026-07-24',
    closeDate: '2026-10-15',
    lastDate: '2026-10-15',
    vacancies: '18 Openings',
    applyLink: 'https://www.linkedin.com/jobs/search/?keywords=NVIDIA%20CUDA%20Engineer',
    source: 'LinkedIn Verified Jobs',
    isInternship: false,
    postedDate: 'Posted 1d ago',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 90,
    missingSkills: ['CUDA'],
    eligible: true,
    estimatedInterviewProbability: 87
  },
  {
    id: 'job-grab-1',
    company: 'Grab APAC',
    role: 'Backend Microservices Engineer',
    officialSiteRoleName: 'Grab Careers: Software Engineer - Microservices & Go',
    linkedInRoleName: 'LinkedIn: Grab Backend Engineer (Singapore)',
    naukriRoleName: 'Naukri: Grab APAC Software Developer',
    indeedRoleName: 'Indeed: Grab Backend Engineer',
    socialMediaRoleName: 'Glassdoor: Grab Singapore Hiring Drive',
    description: 'Build high-concurrency payment gateway microservices handling millions of daily ride-hailing and food delivery transactions in Go and Kafka.',
    department: 'Computer Science & Engineering',
    skillsRequired: ['Go', 'Java', 'Distributed Systems', 'Kafka', 'Redis', 'SQL'],
    salary: '$85,000 / yr',
    location: 'Singapore / Asia-Pacific (Remote)',
    experience: 'Fresher / 0-1 yr',
    education: 'B.E / B.Tech / Any Graduate',
    minCgpa: 7.0,
    maxBacklogs: 0,
    openDate: '2026-07-26',
    closeDate: '2026-09-30',
    lastDate: '2026-09-30',
    vacancies: '22 Openings',
    applyLink: 'https://www.linkedin.com/jobs/search/?keywords=Grab%20Software%20Engineer',
    source: 'LinkedIn Verified Jobs',
    isInternship: false,
    postedDate: 'Posted 4h ago',
    verifiedDate: 'Verified Today',
    status: 'Verified',
    matchPercentage: 94,
    missingSkills: [],
    eligible: true,
    estimatedInterviewProbability: 91
  }
];

export const generateSkillMatchedJobsForStudent = (profile: UserProfile): JobOpportunity[] => {
  const skills = profile.technicalSkills || [];
  const projects = profile.projects || [];
  const certs = profile.certifications || [];

  // Combine text from skills, projects, and certifications for deep matching
  const allResumeText = [
    ...skills,
    ...projects.map(p => `${p.title} ${p.description} ${(p.techStack || []).join(' ')}`),
    ...certs.map(c => `${c.title} ${c.issuer}`),
    profile.department || ''
  ].join(' ').toLowerCase();

  if (!allResumeText.trim()) return [];

  const customJobs: JobOpportunity[] = [];

  // 1. Deep Match: Game Development, Unity, Blender, 3D Artist, AR/VR, Shaders
  if (allResumeText.includes('unity') || allResumeText.includes('blender') || allResumeText.includes('game') || allResumeText.includes('3d') || allResumeText.includes('artist') || allResumeText.includes('maya')) {
    customJobs.push({
      id: 'job-custom-game-1',
      company: 'Ubisoft Entertainment',
      role: 'Unity 3D Developer & Game Graphics Engineer',
      department: profile.department || 'Electrical & Electronics Engineering',
      skillsRequired: skills.length > 0 ? skills : ['UNITY', 'BLENDER', 'GAME DEVELOPMENT', '3D ARTIST'],
      salary: '₹14,50,000 / yr',
      location: 'Pune / Mumbai (Hybrid)',
      experience: 'Fresher (2026 Batch)',
      education: 'B.E / B.Tech / Any Graduate',
      minCgpa: 6.5,
      maxBacklogs: 0,
      lastDate: '2026-09-25',
      applyLink: getCompanyPortalDeepLink('Ubisoft Entertainment', 'Unity 3D Developer & Game Graphics Engineer', 'LinkedIn'),
      source: 'LinkedIn',
      isInternship: false,
      postedDate: 'Posted 1h ago via LinkedIn',
      verifiedDate: 'Verified Today',
      status: 'Verified',
      matchPercentage: 100,
      missingSkills: [],
      eligible: true,
      estimatedInterviewProbability: 96
    });

    customJobs.push({
      id: 'job-custom-game-2',
      company: 'EA Games (Electronic Arts)',
      role: 'Associate 3D Modeler & Unity Interactive Developer',
      department: profile.department || 'Electrical & Electronics Engineering',
      skillsRequired: skills.length > 0 ? skills : ['UNITY', 'BLENDER', '3D ARTIST', 'GAME DEVELOPMENT'],
      salary: '₹16,00,000 / yr',
      location: 'Hyderabad (EA India)',
      experience: 'Fresher (0-1 yr)',
      education: 'B.Tech / B.E / B.Sc',
      minCgpa: 7.0,
      maxBacklogs: 0,
      lastDate: '2026-09-28',
      applyLink: getCompanyPortalDeepLink('EA Games (Electronic Arts)', 'Associate 3D Modeler & Unity Interactive Developer', 'Naukri'),
      source: 'Naukri',
      isInternship: false,
      postedDate: 'Posted 3h ago via Naukri',
      verifiedDate: 'Verified Today',
      status: 'Verified',
      matchPercentage: 98,
      missingSkills: [],
      eligible: true,
      estimatedInterviewProbability: 94
    });

    customJobs.push({
      id: 'job-custom-game-3',
      company: 'Rockstar Games India',
      role: 'Game Physics & Shader Renderer Developer',
      department: profile.department || 'Electrical & Electronics Engineering',
      skillsRequired: skills.length > 0 ? skills : ['UNITY', 'BLENDER', '3D ARTIST', 'C++'],
      salary: '₹18,00,000 / yr',
      location: 'Bengaluru (Rockstar India)',
      experience: 'Fresher (0-2 yrs)',
      education: 'B.E / B.Tech / MCA',
      minCgpa: 7.0,
      maxBacklogs: 0,
      lastDate: '2026-09-30',
      applyLink: getCompanyPortalDeepLink('Rockstar Games India', 'Game Physics & Shader Renderer Developer', 'Official Careers'),
      source: 'Official Careers',
      isInternship: false,
      postedDate: 'Posted 4h ago',
      verifiedDate: 'Verified Today',
      status: 'Verified',
      matchPercentage: 95,
      missingSkills: [],
      eligible: true,
      estimatedInterviewProbability: 92
    });
  }

  // 2. Deep Match: Electrical & Electronics Engineering (EEE/ECE, Power Systems, Microcontrollers, Embedded)
  if (allResumeText.includes('electrical') || allResumeText.includes('electronics') || allResumeText.includes('eee') || allResumeText.includes('ece') || allResumeText.includes('embedded') || allResumeText.includes('circuit') || allResumeText.includes('power')) {
    customJobs.push({
      id: 'job-custom-eee-1',
      company: 'Schneider Electric',
      role: 'Electrical & Power Automation Control Engineer GET',
      department: profile.department || 'Electrical & Electronics Engineering',
      skillsRequired: ['Electrical Power Systems', 'PLC Programming', 'MATLAB', 'Embedded Systems', 'Circuit Design'],
      salary: '₹12,50,000 / yr',
      location: 'Bengaluru / Chennai',
      experience: 'Fresher (GET 2026)',
      education: 'B.E / B.Tech EEE, ECE',
      minCgpa: 7.0,
      maxBacklogs: 0,
      lastDate: '2026-09-20',
      applyLink: getCompanyPortalDeepLink('Schneider Electric', 'Electrical & Power Automation Control Engineer GET', 'Official Careers'),
      source: 'Official Careers',
      isInternship: false,
      postedDate: 'Posted 2h ago',
      verifiedDate: 'Verified Today',
      status: 'Verified',
      matchPercentage: 95,
      missingSkills: [],
      eligible: true,
      estimatedInterviewProbability: 92
    });
  }

  return customJobs;
};

export const mockTestsCatalog: MockTest[] = [];
export const dailyTasksList: DailyTask[] = [];
